# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20180125_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_of_receiver', to='user_app.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_of_author', to='user_app.User'),
        ),
    ]
